---
title: "Project-1"
author: "Daisy Ann O. Pajarillo"
date: "2022-12-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Install Library
```{r, vector = TRUE}
library(twitteR)
library(tm)
library(dplyr)
library(tidyr)
library(plotly)
library(ggplot2)
library(RColorBrewer)
library(tidytext)
library(wordcloud)
library(wordcloud2)

```

Setup Credentials
```{r, vector = TRUE}
setup_twitter_oauth(consumer_key = "TdxvgnZD24KkRNeNECutJbdSR",
                    consumer_secret = "MtsvAL2uR56Ii3F95L6QK7cdxTX5QL6o5Pnyqnq5W4VdsCREhC",
                    access_token ="1594988417439305728-T7ZaXiD0vAET3sBrfQlMJUMeJ4blo1",
                    access_secret = "hZH38SNVuWu6NrW7YIwJGP1v1WwH1OEvtgihiaJgxPhRh")
```



```{r, vector = TRUE}
gg <- searchTwitter("Technology -filter:retweets", n=10000, lang = "en",
                   since = "2022-12-1", until = "2022-12-8", retryOnRateLimit = 120)
gg

```


Convert data into dataframe and save file into R.data

```{r, vector = TRUE}
ggDF <- twListToDF(gg)
ggDF
class(ggDF)
names(ggDF)
View(ggDF)
head(ggDF)[1:5]
head(ggDF$text)[1:5]

  save(ggDF, file = "ggDF.Rdata")
load(file = "ggDF.Rdata")
```


Checking for missing values in a data frame
```{r, vector = TRUE}
ggDF$text <- sapply(ggDF$text, function(x) iconv(enc2utf8(x), sub = "byte"))
head(ggDF$text)

sapply(ggDF, function(x) sum(is.na(x)))
```

```{r, vector = TRUE}
gg1DF <- ggDF %>%
  select(screenName,text,created,statusSource)
gg1DF
```
saving file as Rdata
```{r, vector = TRUE}
save(gg1DF, file = "gg1DF.Rdata")
write.csv(gg1DF, file = "gg1DF.csv")
```

Grouping Data created
```{r, vector = TRUE}
gg1DF%>%group_by(1) %>% summarise(max = max(created), min = min(created))

gg1DF%>%mutate(Created_At_Round = created%>%round(units = 'hours')%>%as.POSIXct())

gg1DF %>%pull(created) %>% min()
gg1DF %>%pull(created) %>% max()
```


plot
```{r, vector = TRUE}
ggplot(data = gg1DF, aes(x = created)) +
  geom_histogram(aes(fill = ..count..)) +
  theme(legend.position = "right") +
  xlab("Time") + ylab("Number of tweets") + 
  scale_fill_gradient(low = "black", high = "grey")

```


Analysis using the source
```{r, vector = TRUE}

encodeSource <- function(x) {
  if(grepl(">Twitter for iPhone</a>", x)){
    "iphone"
  }else if(grepl(">Twitter for iPad</a>", x)){
    "ipad"
  }else if(grepl(">Twitter for Android</a>", x)){
    "android"
  } else if(grepl(">Twitter Web Client</a>", x)){
    "Web"
  } else if(grepl(">Twitter for Windows Phone</a>", x)){
    "windows phone"
  }else if(grepl(">dlvr.it</a>", x)){
    "dlvr.it"
  }else if(grepl(">IFTTT</a>", x)){
    "ifttt"
  }else if(grepl(">Facebook</a>", x)){ 
    
    "facebook"
  }else {
    "others"
  }
}


gg1DF$tweetSource = sapply(gg1DF$statusSource, encodeSource)

tweet_appSource <- gg1DF %>% 
  select(tweetSource) %>%
  group_by(tweetSource) %>%
  summarize(count=n()) %>%
  arrange(desc(count)) 




```



plotting using geom_bar() - bar graph
```{r,vector = TRUE}

ggplot(gg1DF[gg1DF$tweetSource != 'others',], aes(tweetSource, fill = tweetSource)) +
  geom_bar() +
  theme(legend.position="none",
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylab("Number of tweets") +
  ggtitle("Tweets by Source")

```


```{r, vector = TRUE}
tweet_appScreen <- gg1DF %>%
  select(screenName) %>%
  group_by(screenName) %>%
  summarize(count=n()) %>%
  arrange(desc(count)) 







```



convert to Corpus
```{r, vector = TRUE}

namesCorpus <- Corpus(VectorSource(gg1DF$screenName))  


```


using ScreenName
```{r, vector = TRUE}

class(gg1DF$screenName)
str(namesCorpus)
class(namesCorpus)
```


Create a wordcloud from the screenName
```{r, vector = TRUE}

pal <- brewer.pal(8, "Dark2")
pal <- pal[-(1:4)]
set.seed(123)

par(mar = c(0,0,0,0), mfrow = c(1,1))

wordcloud(words = namesCorpus, scale=c(3,0.5),
          max.words=500,
          random.order=FALSE,
          rot.per=0.5,
          use.r.layout=TRUE,
          colors=pal)

```





